version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  capture-service:
    build:
      context: ./capture-service
      dockerfile: Dockerfile
    network_mode: "host"
    depends_on:
      - redis

  analysis-service:
    build:
      context: ./analysis-service-2
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - redis
      - capture-service
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - VIRUSTOTAL_API_KEY=${VIRUSTOTAL_API_KEY:-}
      - ABUSEIPDB_API_KEY=${ABUSEIPDB_API_KEY:-}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - analysis-service
    environment:
      - NEXT_PUBLIC_API_URL=http://analysis-service:3001

volumes:
  redis-data: 